## Madeira landings (CL)
### Landings by country
```{r, echo = FALSE, warning = FALSE, message = FALSE, results = "asis", dpi=100, fig.width=6,fig.height=6,fig.cap='**Figure 82**:Landings (1000 t) by Country'}

barplot(data = cl %>%
  filter(CLjurisdictionArea=='Madeira'), 
      x = "CLvesselFlagCountry",
      y = "CLscientificWeight_1000ton",
      #title = "Landings (1000 t) by Country",
      ylab = "Sum of Landings (1000 t)",
      col_cou = T)
```

### Landings by species {.tabset}
#### species
```{r, echo = FALSE, warning = FALSE, message = FALSE, results = "asis", dpi=100, fig.width=6,fig.height=6, fig.cap='**Figure 83**: Landings of the 20 main Species.'}

sub_cl<- cl%>%
  filter(CLjurisdictionArea=='Madeira')%>%
  group_by(CLyear,SpeciesLaName) %>%
  summarise(CLscientificWeight_1000ton = sum(CLscientificWeight_1000ton)) %>%
  top_n(20, wt=CLscientificWeight_1000ton)
barplot(data = sub_cl, 
      x = "SpeciesLaName",
      y = "CLscientificWeight_1000ton",
      #title = "Landings (1000 t) by Species",
      ylab = "Sum of Landings (1000 t)")

```

#### species catch group
```{r, echo = FALSE, warning = FALSE, message = FALSE, results = "asis", dpi=100, fig.width=6,fig.height=6, fig.cap='**Figure 84**: Sum of the landings by species catch group.'}

barplot(data = cl%>%
  filter(CLjurisdictionArea=='Madeira'), 
      x = "CatchGroup",
      y = "CLscientificWeight_1000ton",
      #title = "Landings (1000 t) by Species Catch Group",
      ylab = "Landings (1000 t)")
```

### Landings by metier {.tabset}
#### metier lvl5
```{r, echo = FALSE, warning = FALSE, message = FALSE, results = "asis", dpi=100, fig.width=7,fig.height=7, fig.cap='**Figure 85**: Total landings by metier level 5 (top 20).'}
#data prep
sub_cl_top <- cl%>%
  filter(CLjurisdictionArea=='Madeira')%>%
  mutate(CLmetier5 = substr(CLmetier6, 1, 7))%>%
  group_by(CLyear, CLmetier5) %>%
  summarise(CLscientificWeight_1000ton = sum(CLscientificWeight_1000ton)) %>%
  top_n(20)


barplot(data = sub_cl_top,
      x = "CLmetier5",
      y = "CLscientificWeight_1000ton",
     # title = "Landings (1000 t) by Metier Lvl5",
      ylab = "Proportion of Landings (1000 t)")
```

#### metier lvl6
```{r, echo = FALSE, warning = FALSE, message = FALSE, results = "asis", dpi=100, fig.width=6,fig.height=6, fig.cap='**Figure 86**: Total landings by metier level 6 (top 20).'}
sub_cl_top<- cl%>%
  filter(CLjurisdictionArea=='Madeira')%>%
  group_by(CLyear, CLmetier6) %>%
  summarise(CLscientificWeight_1000ton = sum(CLscientificWeight_1000ton)) %>%
  top_n(20, wt=CLscientificWeight_1000ton)

barplot(data = sub_cl_top, 
      x = "CLmetier6",
      y = "CLscientificWeight_1000ton",
     # title = "Landings (1000 t) by Metier Lvl6",
      ylab = "Sum of Landings (1000 t)")
```

### Landings by harbour{.tabset}
#### harbour
```{r, echo = FALSE, warning = FALSE, message = FALSE, results = "asis", dpi=100, fig.width=6,fig.height=6, fig.cap='**Figure 87**: Total landings of the main harbours (top 20).'}
sub_cl_top<- cl%>%
  filter(CLjurisdictionArea=='Madeira')%>%
  group_by(CLyear, CLlandingLocation) %>%
  summarise(CLscientificWeight_1000ton = sum(CLscientificWeight_1000ton)) %>%
  top_n(20, wt=CLscientificWeight_1000ton)

barplot(data = sub_cl_top, 
      x = "CLlandingLocation",
      y = "CLscientificWeight_1000ton",
      #title = "Landings (1000 t) by Harbours",
      ylab = "Sum of Landings (1000 t)")
```

#### map - harbour
```{r, echo = FALSE, warning = FALSE, message = FALSE, results = "asis", dpi=100, fig.width=6,fig.height=6, fig.cap='**Figure 88**: Map with the landing weight by main harbours (top 20).'}
sub_cl_top %>%  mutate(
         analysis_type = 'sum',
         type_of_threshold = 'none',
         value_of_threshold = NA
       )-> df

if(nrow(df)==0){
  c('No data')
}else{
result <- pointsMap_func2(df,
                          title = '',#'Landings (1000 t) by Harbour',
                          var_name = 'CLscientificWeight_1000ton',
                          facet_name = 'CLyear',
                          var_spatial_name = 'CLlandingLocation',
                          spatial_dataset_name = 'Harbours',
                          spatial_dataset_var_name = 'Harbour',
                          plot_labels = TRUE,
                          saveResults = FALSE,
                          #outputPath,
                          Catch_group_name = NA,
                          extraShp_name = 'Divisionshp',
                          newVarName = NA,
                          addToTitle = NA
                          #,
                          #RCGregion = 'BA'
                         )

  
result
}

```

