# Total landings by harbour (TOP 20) {.tabset}
The plot below shows the total landings in 1000 tons by harbour.

## Clupea harengus - TOP 20 harbours
```{r echo=FALSE, fig.height=6, fig.width=12, message=FALSE, warning=FALSE, dpi=100, results="asis", cache=FALSE}
cl %>%
  filter(CatchGroup == 'small pelagic',
         CLspeciesFaoCode =='HER',
         CLyear == params$year-2) |>
  group_by(CLlandingLocation) |>
  summarise(CLscientificWeight_1000ton = sum(CLscientificWeight_1000ton))|>
  arrange(desc(CLscientificWeight_1000ton)) |>
  top_n(20) |>
  mutate(CLyear = params$year-2)->sub_cl1

cl %>%
  filter(CatchGroup == 'small pelagic',
         CLspeciesFaoCode =='HER',
         CLyear == params$year-1) |>
  group_by(CLlandingLocation) |>
  summarise(CLscientificWeight_1000ton = sum(CLscientificWeight_1000ton))|>
  arrange(desc(CLscientificWeight_1000ton)) |>
  top_n(20) |>
  mutate(CLyear = params$year-1)->sub_cl2

cl %>%
  filter(CatchGroup == 'small pelagic',
         CLspeciesFaoCode =='HER',
         CLyear == params$year) |>
  group_by(CLlandingLocation) |>
  summarise(CLscientificWeight_1000ton = sum(CLscientificWeight_1000ton))|>
  arrange(desc(CLscientificWeight_1000ton)) |>
  top_n(20) |>
  mutate(CLyear = params$year)->sub_cl3

sub_cl <- bind_rows(sub_cl1, sub_cl2, sub_cl3)

sub_cl %>%  mutate(
         analysis_type = 'sum',
         type_of_threshold = 'none',
         value_of_threshold = NA
       )-> df


result <- pointsMap_func2(df,
                          title = '', #Landings (1000 t) by Harbour
                          var_name = 'CLscientificWeight_1000ton',
                          facet_name = 'CLyear',  # Poprawiono
                          var_spatial_name = 'CLlandingLocation',
                          spatial_dataset_name = 'Harbours',
                          spatial_dataset_var_name = 'Harbour',
                          plot_labels = TRUE,
                          saveResults = FALSE,
                          outputPath,
                          Catch_group_name = NA,
                          extraShp_name = 'StatRectshp',
                          newVarName = NA,
                          addToTitle = NA,
                          RCGregion = 'BA'
                         )

  
result
```

## Sprattus sprattus - TOP 20 harbours
\* The coordinates of the LVVNT harbour are not available, so it is not shown on the map.
```{r echo=FALSE, fig.height=6, fig.width=12, message=FALSE, warning=FALSE, dpi=100, results="asis", cache=FALSE}
cl %>%
  filter(CatchGroup == 'small pelagic',
         CLspeciesFaoCode =='SPR',
         CLyear == params$year-2) |>
  group_by(CLlandingLocation) |>
  summarise(CLscientificWeight_1000ton = sum(CLscientificWeight_1000ton))|>
  arrange(desc(CLscientificWeight_1000ton)) |>
  top_n(20) |>
  mutate(CLyear = params$year-2)->sub_cl1

cl %>%
  filter(CatchGroup == 'small pelagic',
         CLspeciesFaoCode =='SPR',
         CLyear == params$year-1) |>
  group_by(CLlandingLocation) |>
  summarise(CLscientificWeight_1000ton = sum(CLscientificWeight_1000ton))|>
  arrange(desc(CLscientificWeight_1000ton)) |>
  top_n(20) |>
  mutate(CLyear = params$year-1)->sub_cl2

cl %>%
  filter(CatchGroup == 'small pelagic',
         CLspeciesFaoCode =='SPR',
         CLyear == params$year) |>
  group_by(CLlandingLocation) |>
  summarise(CLscientificWeight_1000ton = sum(CLscientificWeight_1000ton))|>
  arrange(desc(CLscientificWeight_1000ton)) |>
  top_n(20) |>
  mutate(CLyear = params$year)->sub_cl3

sub_cl <- bind_rows(sub_cl1, sub_cl2, sub_cl3)

sub_cl %>%  mutate(
         analysis_type = 'sum',
         type_of_threshold = 'none',
         value_of_threshold = NA
       )-> df


result <- pointsMap_func2(df,
                          title = '', #Landings (1000 t) by Harbour
                          var_name = 'CLscientificWeight_1000ton',
                          facet_name = 'CLyear',
                          var_spatial_name = 'CLlandingLocation',
                          spatial_dataset_name = 'Harbours',
                          spatial_dataset_var_name = 'Harbour',
                          plot_labels = TRUE,
                          saveResults = FALSE,
                          outputPath,
                          Catch_group_name = NA,
                          extraShp_name = 'StatRectshp',
                          newVarName = NA,
                          addToTitle = NA,
                          RCGregion = 'BA'
                         )

  
result
```